# Fallstudie

## Import Pakete

In [80]:
import pandas as pd
import numpy as np
import sqlite3
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sqlalchemy import create_engine 
from sklearn.neighbors import KNeighborsClassifier
import pickle

## Import Datenbank

In [81]:
cnx = create_engine('sqlite:///C:/Users/lucaf/Documents/Notebooks/Fallstudie/Kundendaten.db').connect() 
  
df = pd.read_sql_table('testdaten', cnx) 

In [82]:
#df = df.head(100000)

## Datenmodellierung 

In [83]:
df = df.drop(["Datum"], 1)
df = df.drop(["Anzahl"], 1)
df = df.drop(["Gewinn"], 1)
df = df.drop(["Jahr"], 1)
df = df.drop(["Monat"], 1)
df = df.drop(["Tag"], 1)
df = df.drop(["index"], 1)

In [84]:
df.head()

Alter Geschlecht                  Job         Familienstand Kinder  \
0     47          M  Öffentlicher Dienst           verheiratet     ja   
1     45          M      Ingenieurswesen           verheiratet     ja   
2     23          W             Handwerk                 ledig   nein   
3     60          W        Administrativ           verheiratet     ja   
4     60          M           Informatik  aufgelöste Beziehung     ja   

     Gehalt Angebotenes Produkt Gekauft  
0   42000.0          Depotkonto    nein  
1   76000.0      Bausparvertrag      ja  
2   23000.0              Kredit    nein  
3   57000.0              Kredit    nein  
4  123000.0              Kredit    nein

In [85]:
pd.options.mode.chained_assignment = None  # default='warn'
df["Altersgruppe"] = ">65"

df["Altersgruppe"][df["Alter"] > 65] = ">65"
df["Altersgruppe"][(df["Alter"] >= 50) & (df["Alter"] < 65)] = "50 - 65"
df["Altersgruppe"][(df["Alter"] >= 30) & (df["Alter"] < 50)] = "30 - 49"
df["Altersgruppe"][(df["Alter"] >= 18) & (df["Alter"] < 30)] = "18 - 29"
df["Altersgruppe"][df["Alter"] < 18] = "<18"

In [86]:
df["balance_cat"] = "> 100000"

df["balance_cat"][df["Gehalt"] > 100000] = "> 100000"
df["balance_cat"][(df["Gehalt"] >= 80000) & (df["Gehalt"] < 100000)] = "80000 - 99999"
df["balance_cat"][(df["Gehalt"] >= 60000) & (df["Gehalt"] < 80000)] = "60000 - 79999"
df["balance_cat"][(df["Gehalt"] >= 40000) & (df["Gehalt"] < 60000)] = "40000 - 59999"
df["balance_cat"][(df["Gehalt"] >= 20000) & (df["Gehalt"] < 40000)] = "20000 - 39999"
df["balance_cat"][(df["Gehalt"] >= 0) & (df["Gehalt"] < 20000)] = "0 - 19999"
df["balance_cat"][df["Gehalt"] < 0] = "< 0"

In [87]:
df["Produkt"] = df["Angebotenes Produkt"]
df["Produkt"] = df["Produkt"].replace(["Girokonto", "Kredit","Tagesgeldkonto","Depotkonto", "Altersvorsorge","Versicherung", "Bausparvertrag"],[1,2,3,4,5,6,7])
df = df.drop(["Angebotenes Produkt"], 1)

In [88]:

df["Job"] = df["Job"].replace(["Studium", "Öffentlicher Dienst", "Rente", "Informatik", "Handel", "Handwerk", "Administrativ", "Ingenieurswesen", "Management", "Arbeitslos"],[0,1,2,3,4,5,6,7,8,9])

In [89]:
df["Geschlecht"] = df["Geschlecht"].replace(["M", "W", "D"],[1,2,3])

In [90]:
df["Familienstand"] = df["Familienstand"].replace(["verheiratet", "ledig", "aufgelöste Beziehung"],[1,2,3])

In [91]:
df["Kinder"] = df["Kinder"].replace(["ja", "nein"],[1,0])

In [92]:
df["Altersgruppe"] = df["Altersgruppe"].replace(["<18", "18 - 29", "30 - 49", "50 - 65", ">65"],[0,1,2,3,4])

In [93]:
df["balance_cat"] = df["balance_cat"].replace(["< 0", "0 - 19999", "20000 - 39999", "40000 - 59999", "60000 - 79999", "80000 - 99999", "> 100000"],[1,2,3,4,5,6,7])
df = df.drop(["Gehalt"], axis=1)

In [94]:
df = df.drop(["Alter"], axis=1)

In [95]:
df["Gekauft"] = df["Gekauft"].replace(["nein", "ja"],[0, 1])

In [96]:
labels = np.array(df["Gekauft"])
#labels = np.array(df["Produkt"])

In [97]:
dfTest = df

In [98]:
df = df.drop(["Gekauft"], axis=1)
#df = df.drop(["Produkt"], axis=1)

In [99]:
df_list = list(df.columns)

## Algorithmen

### Trainings- und Testdaten vorbereiten

In [100]:
df = np.array(df)

In [101]:
train_data, test_data, train_labels, test_labels = train_test_split(df, labels, test_size = 0.25, random_state = 42)

In [102]:
print('Training Features Shape:', train_data.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_data.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (285519, 7)
Training Labels Shape: (285519,)
Testing Features Shape: (95173, 7)
Testing Labels Shape: (95173,)


### RANDOM FOREST CLASSIFIER

In [58]:
rf = RandomForestClassifier(n_estimators = 1000, random_state = 42)

In [59]:
rf.fit(train_data, train_labels);

In [60]:
pred_rf = rf.predict(test_data)


In [61]:
errors_rf = abs(pred_rf - test_labels)
errors_rf = [x for x in errors_rf if x != 0]

In [62]:
print(f"Accuracy RF = {(len(test_labels)-len(errors_rf))/len(test_labels)}")

Accuracy RF = 0.70636


In [63]:
confusion_matrix_rf = sklearn.metrics.confusion_matrix(test_labels, pred_rf)
tn_rf, fp_rf, fn_rf, tp_rf = confusion_matrix_rf.ravel()

Precision_rf = tp_rf/(tp_rf+fp_rf)
Recall_rf = tp_rf/(tp_rf+fn_rf)
F1_rf = 2*((Precision_rf*Recall_rf)/(Precision_rf+Recall_rf))

print(f"Precision RF = {Precision_rf}")
print(f"Recall Rf = {Recall_rf}")
print(f"F1 Score RF = {F1_rf}")

Precision RF = 0.5376899696048633
Recall Rf = 0.23310054025563315
F1 Score RF = 0.3252137144958177


### K NEAREST NEIGHBORS

In [64]:
classifier = KNeighborsClassifier(n_neighbors=7)

In [65]:
classifier.fit(train_data, train_labels)

KNeighborsClassifier(n_neighbors=7)

In [66]:
pred_knn = classifier.predict(test_data)

In [67]:
errors_knn = abs(pred_knn - test_labels)
errors_knn = [x for x in errors_knn if x != 0]

In [68]:
print(f"Accuracy KNN = {(len(test_labels)-len(errors_knn))/len(test_labels)}")

Accuracy KNN = 0.68296


In [69]:
confusion_matrix_knn = sklearn.metrics.confusion_matrix(test_labels, pred_knn)
tn_knn, fp_knn, fn_knn, tp_knn = confusion_matrix_knn.ravel()

Precision_knn = tp_knn/(tp_knn+fp_knn)
Recall_knn = tp_knn/(tp_knn+fn_knn)
F1_knn = 2*((Precision_knn*Recall_knn)/(Precision_knn+Recall_knn))

print(f"Precision KNN = {Precision_knn}")
print(f"Recall KNN = {Recall_knn}")
print(f"F1 Score KNN = {F1_knn}")


Precision KNN = 0.4654500717654296
Recall KNN = 0.2991171432336276
F1 Score KNN = 0.36419059842772333


### XGBoost Classifier

In [103]:
model = XGBClassifier()

In [104]:
model.fit(train_data, train_labels)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [105]:
pred_xgb = model.predict(test_data)

In [106]:
errors_xgb = abs(pred_xgb - test_labels)
errors_xgb = [x for x in errors_xgb if x != 0]

In [107]:
print(f"Accuracy XGB = {(len(test_labels)-len(errors_xgb))/len(test_labels)}")

Accuracy XGB = 0.7209607766908682


In [108]:
confusion_matrix_xgb = sklearn.metrics.confusion_matrix(test_labels, pred_xgb)
tn_xgb, fp_xgb, fn_xgb, tp_xgb = confusion_matrix_xgb.ravel()

Precision_xgb = tp_xgb/(tp_xgb+fp_xgb)
Recall_xgb = tp_xgb/(tp_xgb+fn_xgb)
F1_xgb = 2*((Precision_xgb*Recall_xgb)/(Precision_xgb+Recall_xgb))

print(f"Precision xgb = {Precision_xgb}")
print(f"Recall xgb = {Recall_xgb}")
print(f"F1 Score xgb = {F1_xgb}")


Precision xgb = 0.5953931383030421
Recall xgb = 0.21479663394109397
F1 Score xgb = 0.3156999665026154


## Funktion für Applikation

In [76]:
for x in range(1,8):
     print(model.predict_proba(np.array([[2,0,2,0,1,2,x]])).reshape((1,-1)))
        
        
def vorschlag(kunde):
    kunde = np.array(kunde).reshape((1,-1))
    
    kunde[0][6] = 1
    prob1 = model.predict_proba(kunde)[0][1]
    
    kunde[0][6] = 2
    prob2 = model.predict_proba(kunde)[0][1]
    
    kunde[0][6] = 3
    prob3 = model.predict_proba(kunde)[0][1]
    
    kunde[0][6] = 4
    prob4 = model.predict_proba(kunde)[0][1]
    
    kunde[0][6] = 5
    prob5 = model.predict_proba(kunde)[0][1]
    
    kunde[0][6] = 6
    prob6 = model.predict_proba(kunde)[0][1]
    
    kunde[0][6] = 7
    prob7 = model.predict_proba(kunde)[0][1]
    
    produkt = {"Girokonto":prob1,"Kredit":prob2, "Tagesgeldkonto":prob3, "Depotkonto":prob4, "Altersvorsorge":prob5, "Versicherung":prob6, "Bausparvertrag":prob7}
    
    print(f"Top 3 Produktvorschläge:")
    print(f"1. {sorted(produkt, key=produkt.get, reverse=True)[:3][0]} mit {round((produkt.get(sorted(produkt, key=produkt.get, reverse=True)[:3][0])*100),2)}% Erfolgschance")
    print(f"2. {sorted(produkt, key=produkt.get, reverse=True)[:3][1]} mit {round((produkt.get(sorted(produkt, key=produkt.get, reverse=True)[:3][1])*100),2)}% Erfolgschance")
    print(f"3. {sorted(produkt, key=produkt.get, reverse=True)[:3][2]} mit {round((produkt.get(sorted(produkt, key=produkt.get, reverse=True)[:3][2])*100),2)}% Erfolgschance")
    

[[0.60975397 0.39024603]]
[[0.88520294 0.11479708]]
[[0.9072776  0.09272243]]
[[0.82347625 0.17652376]]
[[0.8876212 0.1123788]]
[[0.91863555 0.08136448]]
[[0.90118986 0.09881011]]


In [77]:
vorschlag(np.array([[2,0,2,0,1,2,x]]).reshape((1,-1)))


Top 3 Produktvorschläge:
1. Girokonto mit 39.02% Erfolgschance
2. Depotkonto mit 17.65% Erfolgschance
3. Kredit mit 11.48% Erfolgschance


In [78]:
filename = 'jungbank_xgb.sav'
pickle.dump(model, open(filename, 'wb'))

In [79]:
dfTest.head()

Geschlecht  Job  Familienstand  Kinder  Gekauft  Altersgruppe  balance_cat  \
0           1    1              1       1        0             2            4   
1           1    7              1       1        1             2            5   
2           2    5              2       0        0             1            3   
3           2    6              1       1        0             3            4   
4           1    3              3       1        0             3            7   

   Produkt  
0        4  
1        7  
2        2  
3        2  
4        2